// prettier-ignore
export const navItems = [
  {
    text: "Venue",
    url: "/venue",
    img: "",
    img2: "",
    imgColoured: "",
    underline: "https://crosby-wedding.s3.eu-west-2.amazonaws.com/underlines/flower-underline.webp",
    underlineColoured: "",
  },
  {
    text: "Food",
    url: "/food",
    img: "",
    img2: "",
    imgColoured: "",
    underline: "https://crosby-wedding.s3.eu-west-2.amazonaws.com/underlines/flower-underline-4.webp",
    underlineColoured: "",
  },
  {
    text: "",
    url: "/",
    img: "https://crosby-wedding.s3.eu-west-2.amazonaws.com/logo-ring-trans.webp",
    img2: "https://crosby-wedding.s3.eu-west-2.amazonaws.com/M-and-K-logo-trans.webp",
    imgColoured: "",
    underline: "",
    underlineColoured: "",
  },
  {
    text: "Schedule",
    url: "/schedule",
    img: "",
    img2: "",
    imgColoured: "",
    underline: "https://crosby-wedding.s3.eu-west-2.amazonaws.com/underlines/flower-underline-6.webp",
    underlineColoured: "",
  },
  {
    text: "RSVP",
    url: "/rsvp",
    img: "",
    img2: "",
    imgColoured: "",
    underline: "https://crosby-wedding.s3.eu-west-2.amazonaws.com/underlines/flower-underline-2.webp",
    underlineColoured: "",
  },
]
